import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import type { Metadata } from "next";
import "./globals.css";

import {
    ColorSchemeScript,
    MantineProvider,
    createTheme,
    mantineHtmlProps,
} from "@mantine/core";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const theme = createTheme({
    fontFamily: "Open Sans, sans-serif",
    primaryColor: "cyan",
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" {...mantineHtmlProps}>
            <head>
                <ColorSchemeScript />
            </head>
            <body>
                <MantineProvider theme={theme}>{children}</MantineProvider>
            </body>
        </html>
    );
}
